using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class VRMenuBuilder : MonoBehaviour
{
    [Header("References")]
        public Transform content;
            public Button buttonPrefab;
                public Toggle togglePrefab;

                    [Header("Menu")]
                        public StandaloneVRMenu menu;

                            private void Start()
                                {
                                        BuildMenu();
                                            }

                                                public void BuildMenu()
                                                    {
                                                            if (content == null)
                                                                    {
                                                                                Debug.LogError("VRMenuBuilder: Content is not assigned.");
                                                                                            return;
                                                                                                    }

                                                                                                            if (buttonPrefab == null)
                                                                                                                    {
                                                                                                                                Debug.LogError("VRMenuBuilder: Button prefab is not assigned.");
                                                                                                                                            return;
                                                                                                                                                    }

                                                                                                                                                            if (togglePrefab == null)
                                                                                                                                                                    {
                                                                                                                                                                                Debug.LogError("VRMenuBuilder: Toggle prefab is not assigned.");
                                                                                                                                                                                            return;
                                                                                                                                                                                                    }

                                                                                                                                                                                                            CreateToggle(
                                                                                                                                                                                                                        "Player Outline",
                                                                                                                                                                                                                                    menu != null && menu.playerOutline,
                                                                                                                                                                                                                                                value =>
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                            if (menu != null)
                                                                                                                                                                                                                                                                                                menu.playerOutline = value;
                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                    CreateToggle(
                                                                                                                                                                                                                                                                                                                                "Show Names",
                                                                                                                                                                                                                                                                                                                                            menu != null && menu.showNames,
                                                                                                                                                                                                                                                                                                                                                        value =>
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                    if (menu != null)
                                                                                                                                                                                                                                                                                                                                                                                                        menu.showNames = value;
                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                            CreateToggle(
                                                                                                                                                                                                                                                                                                                                                                                                                                        "Enhanced Graphics",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    menu != null && menu.enhancedGraphics,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                value =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (menu != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                menu.enhancedGraphics = value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CreateToggle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Controller Vibration",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            menu != null && menu.vibration,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (menu != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        menu.vibration = value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CreateToggle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Left-Handed Mode",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    menu != null && menu.leftHanded,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (menu != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                menu.leftHanded = value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CreateButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Test Feature",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            () => Debug.Log("Test feature activated."));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CreateButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Close Menu",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            () =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (menu != null && menu.menuRoot != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            menu.menuRoot.SetActive(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void CreateButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        string label,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                UnityEngine.Events.UnityAction action)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Button button = Instantiate(buttonPrefab, content);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TMP_Text text =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                button.GetComponentInChildren<TMP_Text>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (text != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text.text = label;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            button.onClick.AddListener(action);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private void CreateToggle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            string label,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bool initialValue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            UnityEngine.Events.UnityAction<bool> action)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Toggle toggle = Instantiate(togglePrefab, content);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TMP_Text text =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            toggle.GetComponentInChildren<TMP_Text>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (text != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text.text = label;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        toggle.isOn = initialValue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                toggle.onValueChanged.AddListener(action);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }